### ISSUE TITLE
Dependency issue for macOS with Apple Silicon Chips: numactl

### ISSUE THREAD

**Issue by valentinaschueller** [schreiberx/sweet#31]
At the moment, SWEET can not be installed on any Mac with an Apple Silicon chip, due to SWEET's dependency on [numactl](https://github.com/numactl/numactl).
Is it possible to remove this dependency? If not, this should mentioned somewhere in the documentation/README/tutorials.

**Comment by schreiberx** [comment]
Resolved with newest PR
