### ISSUE TITLE
Installing SWEET on macOS: miniconda not actually required for compilation

### ISSUE THREAD

**Issue by valentinaschueller** [schreiberx/sweet#33]
We should update [INSTALL.md](https://github.com/schreiberx/sweet/blob/master/INSTALL.md)/[INSTALL_MACOS.md](https://github.com/schreiberx/sweet/blob/master/INSTALL_MACOSX.md) to make clear that miniconda does not have to be installed when setting up SWEET (Install file for macOS recommends to install Python packages via Homebrew)

**Comment by schreiberx** [comment]
Resolved with newest PR
